name = "go-module-proxy"
main = "worker/index.ts"
compatibility_date = "2025-10-03"
preview_urls = true

[build]
command = "npm run build"

[assets]
binding = "ASSETS"
directory = "./build"
html_handling = "drop-trailing-slash"
not_found_handling = "none"

[[routes]]
pattern = "go.ufukty.com"
zone_name = "ufukty.com"
custom_domain = true
